name: Build on PR

on: pull_request

jobs:
  build:
    if: "${{ github.event.pull_request.head.repo.full_name==github.repository }}"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run build
